/**
 * eCommerceMarketplace notification event codes.
 */
export const NotificationEventCodes = {
    TASK_REQUEST_CREATED: "TASK_REQUEST_CREATED",
    TASK_REQUEST_CLOSED: "TASK_REQUEST_CLOSED",
    BID_ACCEPTED: "BID_ACCEPTED",
    BID_REJECTED: "BID_REJECTED",
    ORDER_CREATED_FROM_LISTING: "ORDER_CREATED_FROM_LISTING",
    ORDER_ACCEPTED: "ORDER_ACCEPTED",
    ORDER_STARTED: "ORDER_STARTED",
    ORDER_CANCELLED: "ORDER_CANCELLED",
    ORDER_EXTENDED: "ORDER_EXTENDED",
    ORDER_DELIVERY_SUBMITTED: "ORDER_DELIVERY_SUBMITTED",
    ORDER_DELIVERY_ACCEPTED: "ORDER_DELIVERY_ACCEPTED",
    ORDER_REVISION_REQUESTED: "ORDER_REVISION_REQUESTED",
} as const;
