/**
 * Stable identity markers for marketplace demo/default rows.
 *
 * Every seeded document has to be findable again on a re-run so the seeders stay
 * idempotent. Schemas differ in where they can carry that marker:
 *
 *   - `name` is auto-generated by most marketplace schemas, but a few accept an
 *     explicit value — those store the marker verbatim via `demoSeedName`.
 *   - `tags[]` carries the marker on listings via `demoSeedTag`.
 *   - free-text fields (review comment, dispute reason) get the marker appended in
 *     brackets via `withDemoSeedMarker`, and are matched back with
 *     `demoSeedMarkerRegex`.
 */

export const DEMO_SEED_PREFIX = "demo-seed";

/** `demo-seed:<seedKey>` — used in `tags[]` and in log lines. */
export function demoSeedTag(seedKey: string): string {
    return `${DEMO_SEED_PREFIX}:${seedKey}`;
}

/** Same marker, used as a document's explicit `name`. */
export function demoSeedName(seedKey: string): string {
    return demoSeedTag(seedKey);
}

/** Appends `[demo-seed:<seedKey>]` to human-readable text without disturbing it. */
export function withDemoSeedMarker(text: string, seedKey: string): string {
    return `${text}\n\n[${demoSeedTag(seedKey)}]`;
}

function escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Matches text produced by `withDemoSeedMarker` for the same seed key. */
export function demoSeedMarkerRegex(seedKey: string): RegExp {
    return new RegExp(`\\[${escapeRegExp(demoSeedTag(seedKey))}\\]`);
}

/** True when the value carries any demo-seed marker (used by cleanup tooling). */
export function isDemoSeeded(value: string | null | undefined): boolean {
    return typeof value === "string" && value.includes(`${DEMO_SEED_PREFIX}:`);
}
